export const testColumns = [
    [
        {   
            field:'',
            type:'checkbox',
            checkbox:true,
            isActive:false,
        },
        {   
            title:'아이디',
            field:'user_pid',
            align:'left',
        },
        {
            type:'sort',
            title:'생년월일',
            field:'birth',
            align:'left',
        },
        {
            title:'이름',
            field:'user_name',
            align:'left', 
        },
        {
            title:'아이디',
            field:'user_id',
            align:'left'
        },
        {
            title:'등록날짜',
            field:'created_at',
            align:'left'
        },
        {
            title:'탈퇴날짜',
            field:'date_widrawal',
            align:'left'
        },
        {
            title:'보기',
            field:'',
            align:'left'
        },
    ],
]


