const Columns = [
    {
        checkbox:true,
        width:'6%',
        align:'center',
        name:'cmplx_pid',
        type:'checkbox',
    },
    {
        title:'글번호',
        width:'6%',
        align:'left',
        name:'cmplx_pid',
    },
    {
        title:'단지명',
        sort:true,
        width:'auto',
        align:'left',
        name:'cmplx_nm'
    },
    {
        title:'도/시',
        sort:true,
        width:'12%',
        align:'left',
        name:'depth1_loc',
    },
    {
        title:'시/군/구',
        sort:true,
        width:'8%',
        name:'depth2_loc',
    },
    {
        title:'내부VR',
        width:'6%',
        name:'in_vr_at',
    },
    {
        title:'외부VR',
        width:'6%',
        name:'out_vr_at',
    },
    {
        title:'단지VR',
        width:'6%',
        name:'cmplx_vr_at',
    },
    {
        title:'수정일시',
        width:'10%',
        name:'updated_at',
        type:'date'
    },
    {
        title:'작성일시',
        width:'10%',
        name:'created_at',
        type:'date'
    },
    {
        title:'상세보기',
        width:'10%',
        name:'상세보기',
        type:'detail'

    },
]
   
   export default Columns